
-- 🔹 users テーブル
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(256) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    full_name VARCHAR(30),
    furigana VARCHAR(30),
    phone VARCHAR(20),
    zipcode VARCHAR(10),
    prefecture VARCHAR(50),
    city VARCHAR(50),
    area VARCHAR(100),
    detailed_address VARCHAR(200),
    birthdate DATE,
    gender VARCHAR(10),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_admin TINYINT(1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 🔹 bukken_detail テーブル
CREATE TABLE bukken_detail (
    id INT AUTO_INCREMENT PRIMARY KEY,
    large_area VARCHAR(50),
    small_area VARCHAR(100),
    address_town VARCHAR(50),
    address_chome VARCHAR(20),
    address_banchi VARCHAR(20),
    address_go VARCHAR(20),
    address_building VARCHAR(50),
    station1 VARCHAR(100),
    station1_walk INT,
    station1_bus INT,
    station2 VARCHAR(100),
    station2_walk INT,
    station2_bus INT,
    station3 VARCHAR(100),
    station4 VARCHAR(100),
    station5 VARCHAR(100),
    rent INT,
    rent_negotiable TINYINT(1),
    building_upper INT,
    building_lower INT,
    floor_type1 VARCHAR(10),
    floor_value1 INT,
    floor_type2 VARCHAR(10),
    floor_value2 INT,
    whole_building TINYINT(1),
    extra_condition TINYINT(1),
    m2 FLOAT,
    tsubo FLOAT,
    structure VARCHAR(100),
    deposit_neg TINYINT(1),
    deposit_month FLOAT,
    deposit_yen INT,
    key_money_neg TINYINT(1),
    key_money_month FLOAT,
    key_money_yen INT,
    contract_period VARCHAR(50),
    state VARCHAR(20),
    transfer_fee FLOAT,
    transfer_neg TINYINT(1),
    maintenance INT,
    maint_neg TINYINT(1),
    prev_tenant VARCHAR(100),
    amortization VARCHAR(100),
    renewal_fee VARCHAR(100),
    built_year INT,
    deal_type VARCHAR(20),
    business_types TEXT,
    remarks TEXT,
    coment VARCHAR(100),
    company VARCHAR(100),
    contact VARCHAR(100),
    company_tel VARCHAR(20),
    company_fax VARCHAR(20),
    memo TEXT,
    open_range TINYINT(1),
    management_id VARCHAR(100),
    customer_registration TINYINT(1),
    image_paths TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
