"""Add key_money_month and key_money_yen

Revision ID: 888701d7dea4
Revises: e739f5dac06f
Create Date: 2025-06-25 15:52:53.443668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '888701d7dea4'
down_revision = 'e739f5dac06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bukken_detail', schema=None) as batch_op:
        batch_op.alter_column('key_money_month',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('key_money_unit')
        batch_op.drop_column('key_money')
        batch_op.drop_column('key_money_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bukken_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_money_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True))
        batch_op.add_column(sa.Column('key_money', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('key_money_unit', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True))
        batch_op.alter_column('key_money_month',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
