"""Add detailed address fields

Revision ID: 9ecb21d0156f
Revises: 888701d7dea4
Create Date: 2025-06-26 10:39:23.002258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ecb21d0156f'
down_revision = '888701d7dea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bukken_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_town', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address_chome', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address_banchi', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address_go', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address_building', sa.String(length=50), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bukken_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.drop_column('address_building')
        batch_op.drop_column('address_go')
        batch_op.drop_column('address_banchi')
        batch_op.drop_column('address_chome')
        batch_op.drop_column('address_town')

    # ### end Alembic commands ###
