"""create_bukken_detail table

Revision ID: de7bc7dc04ee
Revises: 68103daa620f
Create Date: 2025-06-23 10:07:38.058690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7bc7dc04ee'
down_revision = '68103daa620f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bukken_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('large_area', sa.String(length=50), nullable=True),
    sa.Column('small_area', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('rent', sa.Integer(), nullable=True),
    sa.Column('rent_negotiable', sa.Boolean(), nullable=True),
    sa.Column('building_upper', sa.Integer(), nullable=True),
    sa.Column('building_lower', sa.Integer(), nullable=True),
    sa.Column('floor_type', sa.String(length=10), nullable=True),
    sa.Column('stories_up', sa.Integer(), nullable=True),
    sa.Column('stories_down', sa.Integer(), nullable=True),
    sa.Column('whole_building', sa.Boolean(), nullable=True),
    sa.Column('extra_condition', sa.Boolean(), nullable=True),
    sa.Column('m2', sa.Float(), nullable=True),
    sa.Column('tsubo', sa.Float(), nullable=True),
    sa.Column('structure', sa.String(length=100), nullable=True),
    sa.Column('deposit', sa.Float(), nullable=True),
    sa.Column('deposit_unit', sa.String(length=10), nullable=True),
    sa.Column('deposit_neg', sa.Boolean(), nullable=True),
    sa.Column('contract_period', sa.String(length=50), nullable=True),
    sa.Column('key_money', sa.Float(), nullable=True),
    sa.Column('key_money_unit', sa.String(length=10), nullable=True),
    sa.Column('key_money_neg', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('transfer_fee', sa.Float(), nullable=True),
    sa.Column('transfer_neg', sa.Boolean(), nullable=True),
    sa.Column('maintenance', sa.Integer(), nullable=True),
    sa.Column('maint_neg', sa.Boolean(), nullable=True),
    sa.Column('prev_tenant', sa.String(length=100), nullable=True),
    sa.Column('amortization', sa.String(length=100), nullable=True),
    sa.Column('renewal_fee', sa.String(length=100), nullable=True),
    sa.Column('built_year', sa.Integer(), nullable=True),
    sa.Column('deal_type', sa.String(length=20), nullable=True),
    sa.Column('business_types', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('coment', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('company_tel', sa.String(length=20), nullable=True),
    sa.Column('company_fax', sa.String(length=20), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('open_range', sa.Boolean(), nullable=True),
    sa.Column('management_id', sa.String(length=100), nullable=True),
    sa.Column('customer_registration', sa.Boolean(), nullable=True),
    sa.Column('image_paths', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bukken_detail')
    # ### end Alembic commands ###
