"""Refactor deposit fields

Revision ID: e739f5dac06f
Revises: de7bc7dc04ee
Create Date: 2025-06-25 13:20:16.529854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e739f5dac06f'
down_revision = 'de7bc7dc04ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bukken_detail', schema=None) as batch_op:
        batch_op.alter_column('deposit_month',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bukken_detail', schema=None) as batch_op:
        batch_op.alter_column('deposit_month',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
